import RPi.GPIO as GPIO
import time

try:
    while True:

        GPIO.setmode(GPIO.BCM)
        GPIO.setup(2,GPIO.OUT)
        GPIO.setup(3,GPIO.OUT)
        GPIO.setup(4,GPIO.OUT)
        GPIO.setup(9,GPIO.OUT)
        GPIO.setup(10,GPIO.OUT)
        GPIO.setup(17,GPIO.OUT)
        GPIO.setup(22,GPIO.OUT)
        GPIO.setup(27,GPIO.OUT)



        GPIO.output(2,GPIO.HIGH)
        GPIO.output(3,GPIO.HIGH)
        GPIO.output(4,GPIO.HIGH)
        GPIO.output(17,GPIO.HIGH)
        GPIO.output(27,GPIO.HIGH)
        GPIO.output(22,GPIO.HIGH)
        GPIO.output(10,GPIO.HIGH)
        GPIO.output(9,GPIO.HIGH)
        time.sleep(1)
        #GPIO.output(2,GPIO.LOW)
        #GPIO.output(3,GPIO.HIGH)
        #GPIO.output(4,GPIO.HIGH)
        #GPIO.output(17,GPIO.HIGH)
        #GPIO.output(27,GPIO.HIGH)
        #GPIO.output(22,GPIO.HIGH)
        #GPIO.output(10,GPIO.HIGH)
        #GPIO.output(9,GPIO.HIGH)
        #time.sleep(1)
        #GPIO.output(2,GPIO.HIGH)
        #GPIO.output(3,GPIO.LOW)
        #GPIO.output(4,GPIO.HIGH)
        #GPIO.output(17,GPIO.HIGH)
        #GPIO.output(27,GPIO.HIGH)
        #GPIO.output(22,GPIO.HIGH)
        #GPIO.output(10,GPIO.HIGH)
        #GPIO.output(9,GPIO.HIGH)
        #time.sleep(1)
        #GPIO.output(2,GPIO.HIGH)
        #GPIO.output(3,GPIO.HIGH)
        #GPIO.output(4,GPIO.LOW)
        #GPIO.output(17,GPIO.HIGH)
        #GPIO.output(27,GPIO.HIGH)
        #GPIO.output(22,GPIO.HIGH)
        #GPIO.output(10,GPIO.HIGH)
        #GPIO.output(9,GPIO.HIGH)
        #time.sleep(1)
        #GPIO.output(2,GPIO.HIGH)
        #GPIO.output(3,GPIO.HIGH)
        #GPIO.output(4,GPIO.HIGH)
        #GPIO.output(17,GPIO.LOW)
        #GPIO.output(27,GPIO.HIGH)
        #GPIO.output(22,GPIO.HIGH)
        #GPIO.output(10,GPIO.HIGH)
        #GPIO.output(9,GPIO.HIGH)
        #time.sleep(1)
        GPIO.output(2,GPIO.HIGH)
        GPIO.output(3,GPIO.HIGH)
        GPIO.output(4,GPIO.HIGH)
        GPIO.output(17,GPIO.HIGH)
        GPIO.output(27,GPIO.LOW)
        GPIO.output(22,GPIO.HIGH)
        GPIO.output(10,GPIO.HIGH)
        GPIO.output(9,GPIO.HIGH)
        time.sleep(10)
        GPIO.output(2,GPIO.HIGH)
        GPIO.output(3,GPIO.HIGH)
        GPIO.output(4,GPIO.HIGH)
        GPIO.output(17,GPIO.HIGH)
        GPIO.output(27,GPIO.HIGH)
        GPIO.output(22,GPIO.LOW)
        GPIO.output(10,GPIO.HIGH)
        GPIO.output(9,GPIO.HIGH)
        time.sleep(10)
        GPIO.output(2,GPIO.HIGH)
        GPIO.output(3,GPIO.HIGH)
        GPIO.output(4,GPIO.HIGH)
        GPIO.output(17,GPIO.HIGH)
        GPIO.output(27,GPIO.HIGH)
        GPIO.output(22,GPIO.HIGH)
        GPIO.output(10,GPIO.LOW)
        GPIO.output(9,GPIO.HIGH)
        time.sleep(10)
        GPIO.output(2,GPIO.HIGH)
        GPIO.output(3,GPIO.HIGH)
        GPIO.output(4,GPIO.HIGH)
        GPIO.output(17,GPIO.HIGH)
        GPIO.output(27,GPIO.HIGH)
        GPIO.output(22,GPIO.HIGH)
        GPIO.output(10,GPIO.HIGH)
        GPIO.output(9,GPIO.LOW)
        time.sleep(10)
except KeyboardInterrupt:
    GPIO.cleanup()        

